### ISSUE TITLE
TWG870ug 

### ISSUE THREAD

**Issue by davidwozabal** [jclehner/bcm2-utils#1]
I would like to decode the settings file GatewaySettings.bin of my TWG870ug router. From reading the description of the project, this should in principle be possible using your bcm2cfg utility. 

I tried

_./bcm2cfg show -i GatewaySettings.bin_

and got _(decryption failed)_ as answer. I guess that is because there is no profile for my router. 

Do you by any chance have the required information to decode the file?

Cheers,
David

**Comment by jclehner** [comment]
To decrypt and decode this file, I'd need a firmware dump for the TWG870. This could be done using `bcm2dump` and a USB-to-serial adapter, if you're comfortable opening your router. 

Be aware though that `bcm2cfg` currently only shows the settings groups contained in the file, but does not actually decode individual settings (yet). Here's an example:

```
$ bcm2cfg show -i GatewaySettings.bin
FILE: GatewaySettings.bin
============================================
size        20842 bytes                                                                                                                                                          
profile     TC7200 (auto-detected)                                                                                                                                               
checksum    85cf1158fa5f37211b5340634209a50f (ok)                                                                                                                                
key         (none)                                                                                                                                                               
data        20826 bytes (ok)                                                                                                                                                     
padded      no                                                                                                                                                                   
                                                                                                                                                                                 
offset--id---------------type-------------------------------------version------size                                                                                              
     0  38303231 8021    Broadcom Wi-Fi Settings                  0.33        717 b                                                                                              
   717  4344502e CDP.    CDP Settings                             1.5        1506 b                                                                                              
  2223  52472e2e RG..    Broadcom Residential Gateway Settings    0.30       3192 b                                                                                              
  5415  46495245 FIRE    Firewall Settings                        0.7       11267 b                                                                                              
 16682  57694775 WiGu    Broadcom Wi-Fi Guest Network Settings    0.9        4064 b
```

**Comment by davidwozabal** [comment]
Thank you for your quick reply - I will have a look into it. 

Maybe could you first give me some insight, if what I am planning to do will be possible with your utilities? My plan was to decode the GatewaySettings.bin file, change some settings, which can not be changed in the web interface of the router, and finally encode and upload the file to the router.

Would that be in principle possible?

**Comment by jclehner** [comment]
That depends. First off, which settings in particular do you intend to change? As you can see from the sample output I've provided, only some settings groups are actually found in the settings file, while your device's NVRAM contains many more. Which settings groups are included depends on the device.

It's likely that what you intend to do can only be achieved via access to the firmware console, either using a USB-to-serial adapter or `telnet` (if enabled; if not, you *might* be able to activate it using SNMP, if that hasn't been disabled by your ISP).

**Comment by davidwozabal** [comment]
I am hoping that I would be able to set the WiFi channel to 14 to avoid interference on the other channels - obviously this is not possible using the web-interface of the router and the (locked) region settings. 

I have to admit that this is endeavour is built on rather faint hope, since I am not even sure, whether the router can transmit at channel 14 at all. However, if I interpret the output of your tool correctly, it seems that you read out the WiFi settings, which should also contain information on the channel.

I have tried telnet, but the interface seems to be switched off and there is no option to switch it on. However, I did not try your SNMP suggestion and will have a look into it.

**Comment by jclehner** [comment]
I just tried this on a TWG8**5**0 I had lying around, and it *is* possible to change the region in the `GatewaySettings.bin` file to `JP` (Japan being the only country where channel 14 is legal). I've been trying to get hold of a TWG870 for a while now, and I've finally found one. I'm expecting it to be shipped by the end of the week. Support should follow soon after.

**Comment by davidwozabal** [comment]
A wow - that sounds great.

I was already afraid of messing with the hardware myself (not exactly my strong suit).

**Comment by jclehner** [comment]
Hi!

I've added support for the TWG870 in the latest commits. However, my TWG870 has firmware version `STBA.01.38` which doesn't support encryption of `GatewaySettings.bin`; I'm assuming that this was added in a later version, so I can't determine the encryption method used. What is your firmware version?

**Comment by davidwozabal** [comment]
My router reports to have hardware version 1.1 and software version STBA.01.75 which, judging from the version number, should be much more recent than STBA.01.38.

**Comment by jclehner** [comment]
Yes, STBA.01.75 (released 2013) appears to be the latest firmware for this model. The firmware of my device is from 2011. I'll see what I can do...

**Comment by jclehner** [comment]
I've managed to get hold of `STBA.01.75`, and decryption works now. I'd recommend the following approach. First, decrypt the file:

`$ bcm2cfg dec -i GatewaySettings.bin -o GatewaySettings.bin.dec`

Now open it in your favorite hex editor, and look for a two-character string like `EU` (depending on your current region) around offset `0x2e9` (somewhere after `Broadcom`, and `ThomsonAP`). Change this to `JP`. Then run

`$ bcm2cfg enc -i GatewaySettings.bin.dec -o GatewaySettings.bin -P twg870`

If your device accepts the modified file, you should be able to select channel 14 after reboot! Please report back.

**Comment by davidwozabal** [comment]
I followed your instructions, got a bad checksum while encrypting. However, the router accepted the encrypted file and the region settings of the router seems to be changed (luckily the language did not change to Japanese).

I can now select channel 14, but if I do, the WLAN stops working, i.e., I can not catch the signal of my router with any device (not even with the WLAN analyzer of my mobile which also monitors channel 14). 

Do you by chance know whether I have to change some other settings so that the router works with this setting?

**Comment by davidwozabal** [comment]
However, with the new settings I was able to get the router to work on channel 13 (40 Hz bandwidth). This really works much better for me than all the other standard channels (1,6,11) that I could tried till now. 

Close to the router WLAN speed is now close to the speed I get by directly connecting a LAN cable and in the rooms farthest away it is still 1/3 of that (which is much better than what I had till now).

**Thank you very much your efforts really helped me a lot!** I hope that others can also make use of your utility.

**Comment by jclehner** [comment]
Glad it works now. It's possible that the WiFi card in the TWG870 (Broadcom 943224HMS) does not support channel 14!
