### ISSUE TITLE
Unable to detect Arduino interface for Technicolor TC8715D

### ISSUE THREAD

**Issue by DoctorBanner** [jclehner/bcm2-utils#11]
Hello! Hope you're doing well. Incredible project! I spent all day trying to figure out how to do this manually, and then stumbled across this.

I've already got my serial console working with an Arduino on /dev/ttyACM0 and I get the error 

`error: serial: interface auto-detection failed`

Here are the commands I tried:
`sudo ./bcm2dump -P generic dump /dev/ttyACM0,115200 flash image2 image.bin`
`sudo ./bcm2dump -P tc7200 dump /dev/ttyACM0,115200 flash image2 image.bin`

I figured I would also try the TC7200 profile because it could be close enough.

I saw that you were asking for verbose logs in another thread:

```
sudo ./bcm2dump -vv -P tc7200 dump /dev/ttyACM0,115200 flash image2 image.bin

error: serial: interface auto-detection failed

context:
  <== ''
  <== ''
  ==> 'CMM'
```

Any ideas?

**Comment by DoctorBanner** [comment]
While I don't have the firmware file, I did dump the other information you need in order to create a new profile.
[flashshow.txt](https://github.com/jclehner/bcm2-utils/files/2892630/flashshow.txt)
[helpopen.txt](https://github.com/jclehner/bcm2-utils/files/2892634/helpopen.txt)
[version.txt](https://github.com/jclehner/bcm2-utils/files/2892635/version.txt)

**Comment by jclehner** [comment]
What version of `bcm2dump` are you using? `master` or `0.9.3`?

If `master`, please re-run with `-L log.txt` and post that file. If it still doesn't work, try `0.9.3`.

If you're using `0.9.3`, try `master`.

**Comment by jclehner** [comment]
Also, what's your exact wiring and code setup with the Arduino (in case I need to recreate this)?

**Comment by jclehner** [comment]
I just tested this with a TC7200 and an Arduino Uno as a USB-Serial adapter (with the ATmega328p removed) and it worked fine. Those logs would really help!

**Comment by DoctorBanner** [comment]
This is an unsupported TC8715D, not the TC7200. The issue is likely because of that.

I git cloned 2 days ago, so it should be the most recent version. I am using an Arduino Uno R3 and I broke out the soldering iron and 3.3V modded it. [https://learn.adafruit.com/arduino-tips-tricks-and-techniques/3-3v-conversion](url) and added a jumper connecting RST and GND and I'm communicating with the modem over UART with the TX RX and GND pins on the Arduino. I can run 
`sudo screen /dev/ttyACM0 115200`
to establish the console connection. I then arrive at the CM> console.

When I tried it last night, it almost appears to be working sitting at a blinking cursor. I let it run all night but arrived at the console still blinking. I restarted the modem though, and this was the output:

`sudo ./bcm2dump -vv -L log.txt -P generic dump /dev/ttyACM0,115200 flash image2 image.bin

error: serial: interface auto-detection failed

context:
  ==> 'Scanning (pattern) DS Channel at 705000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 699000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 693000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 687000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 681000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 675000000 Hz...'
  ==> 'Scanning DS Channel at 657000000 Hz...(from scan list)'
  ==> 'Scanning DS Channel at 747000000 Hz...(from scan list)'
  ==> 'Scanning DS Channel at 741000000 Hz...(from scan list)'
  ==> 'Scanning DS Channel at 735000000 Hz...(from scan list)'
  ==> 'Scanning DS Channel at 729000000 Hz...(from scan list)'
  ==> 'Scanning DS Channel at 723000000 Hz...(from scan list)'
  ==> 'Scanning DS Channel at 717000000 Hz...(from scan list)'
  ==> 'Scanning DS Channel at 711000000 Hz...(from scan list)'
  ==> 'Scanning DS Channel at 705000000 Hz...(from scan list)'
  ==> 'Scanning DS Channel at 699000000 Hz...(from scan list)'
  ==> 'Scanning DS Channel at 693000000 Hz...(from scan list)'
  ==> 'Scanning DS Channel at 687000000 Hz...(from scan list)'
  ==> 'Scanning DS Channel at 681000000 Hz...(from scan list)'
  ==> 'Scanning DS Channel at 675000000 Hz...(from scan list)'
  ==> 'Scanning DS Channel at 669000000 Hz...(from scan list)'
  ==> 'Scanning DS Channel at 663000000 Hz...(from scan list)'
  ==> 'Scanning (pattern) DS Channel at 669000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 663000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 657000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 651000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 645000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 639000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 633000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 627000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 621000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 615000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 609000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 603000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 597000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 591000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 585000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 579000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 573000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 567000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 561000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 555000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 549000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 543000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 537000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 531000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 525000000 Hz...'
  ==> 'Scanning (pattern) DS Channel at 519000000 Hz...'
  <== ''
  <== ''
`

**Comment by jclehner** [comment]
Try this: login using `screen`, then issue the following command:
```
CM> /docsis_ctl/scan_stop
```
Then re-run `bcm2dump`.

**Comment by DoctorBanner** [comment]
Well that's interesting. It does appear to have generated a file, but I have no idea if it is valid or not.
[image.zip](https://github.com/jclehner/bcm2-utils/files/2898374/image.zip)
[log3.txt](https://github.com/jclehner/bcm2-utils/files/2898373/log3.txt)

**Comment by jclehner** [comment]
1. Did you remove the ATmega328p from the socket? It looks like there's some interference from somewhere, as not all lines are read correctly.

2. What happens if you issue the flash read command manually?
```
/flash/open image2
/flash/readDirect 96 0
```

**Comment by DoctorBanner** [comment]
No, I have not removed the ATmega328p. I will try that next.

`CM/Flash> readDirect 96 0

Reading 96 bytes, starting at an offset of 0 bytes into the region:

a8 ef 01 00   00 00 00 00   58 22 6c f7   00 48 d6 b6 
00 00 00 00   54 43 38 37   31 35 44 2d   30 31 2e 45 
46 2e 30 34   2e 33 32 2e   30 30 2d 31   36 31 31 30 
38 2d 53 2d   46 46 39 5f   67 61 2d 73   65 63 62 6f 
6f 74 2e 00   69 6e 00 00   00 00 00 00   00 48 d5 b6 
00 00 01 00   55 ad 00 00   45 8a e8 db   a8 ef 00 05 
`

**Comment by DoctorBanner** [comment]
That worked. It was in the process of reading, but then I bumped the Arduino and the UART pins disconnected and the modem appears to be bricked. I have a couple other unsupported modems I should be able to help map though.

**Comment by jclehner** [comment]
Sorry to hear that! Did you connect the VCC pin on the TC8715?

**Comment by jclehner** [comment]
Closing this, as the original issue has been resolved!
