### ISSUE TITLE
Sharing Dumps

### ISSUE THREAD

**Issue by nickylimjj** [jclehner/bcm2-utils#19]
Is there a database of dumps we can use? Would be useful to look at it and useit to validate against our own ones. Feel free to DM me if you're willing to share!

**Comment by jclehner** [comment]
I've just uploaded some dumps in a [separate repo](https://github.com/jclehner/bcm2-dumps). Contributions are welcome!

**Comment by nickylimjj** [comment]
Thank you! Much appreciated 🥇
