### ISSUE TITLE
http login

### ISSUE THREAD

**Issue by yctn** [jclehner/bcm2-utils#2]
im trying to find the login for my router but with bcm2cfg get GatewaySettings.bin i only found this:

    http_pass = "admin"
    http_realm = "Technicolor"

i tested the login but it didnt work.
what could the http_realm be? i didnt find a http_user like in ur example

im just trying to find the admin login

**Comment by jclehner** [comment]
I'm not exacltly sure where these two values are used. They are referred to by the firmware as such, but I haven't yet bothered to find out what exactly they are for. The `http_user` is available if your `GatewaySettings.bin` includes the `userif` group, which doesn't apply to all firmwares. What's your ISP?

**Comment by yctn** [comment]
my ISP is ziggo which basicly means UPC is there anywhere on irc or gitter where we can could talk maby? then i can show you the entire dump of information i see maby you can see something in there

**Comment by jclehner** [comment]
Gitter! Closing this now.
