### ISSUE TITLE
Writing a device profile without access to the firmware

### ISSUE THREAD

**Issue by ljani** [jclehner/bcm2-utils#3]
Interesting stuff! Thanks for your work!

From the [`README.md`](https://github.com/jclehner/bcm2-utils/blob/0aa0e31a7a4d553d07092d6cbfa66d4ace7e7a48/README.md#writing-a-device-profile):

> If the device's bootloader serial console has been disabled, and you do not have access to the firmware console (either via serial connection, or telnet), there are ways to enable them (coming soon).

Would you mind expanding this a bit, maybe a few [pointers](https://xkcd.com/138/)? Are you talking about vulnerabilities in web GUIs or are there easier ways?

**Comment by jclehner** [comment]
Some devices have SNMP enabled if disconnected from the coax cable and reset to factory defaults. Vulnerabilities in the WebUI are entirely possible, but I haven't looked for them (yet). Which device are you interested in?

**Comment by ljani** [comment]
Ah, clever, thanks. I did look into SNMP, but I didn't think of disconnecting the cable.

I have a [Sagemcom F@ST 3686 AC](http://www.sagemcom.com/broadband/gateways/home-connectivity/fst-3686-ac/). I'm poking around just for fun and thus I'm not very eager to open it just yet. There's lots of stuff hiding in plain sight (css: `display: none;`) and it makes me wonder what's in `GatewaySettings.bin`.

Now I only need a timeslot when I'm allowed to disconnect the cable, hehe.

**Comment by ljani** [comment]
Hey, you were right! No need to reset factory defaults, just disconnected the cable, rebooted and go this:

```
PORT    STATE SERVICE
161/udp open  snmp
| snmp-info:
|   enterprise: Broadcom Corporation
|   engineIDFormat: octets
|   engineIDData: ...
|   snmpEngineBoots: 1
|_  snmpEngineTime: 27m08s
```

Thanks again.
