### ISSUE TITLE
Looking for TC7200.U bootloader to unbrick it

### ISSUE THREAD

**Issue by yq2018** [jclehner/bcm2-utils#37]
Hello Jclehnet,

Sorry to submit a help in Issues.

I have a TC7200.U from Unitymedia (now Vodafone). A mistake during porting openwrt on it makes it bricked, the flash MX25L8006 is burned out. Now new MX25L8006 is delivered, but there is no backup bootloader image.

Could you share the bootloader?

Thanks a lot.
Qian

**Comment by jclehner** [comment]
You can find the bootloader [here](https://github.com/jclehner/bcm2-dumps/tree/master/tc7200).

**Comment by yq2018** [comment]
Got it.
Thank you very much.

BTW: Partition permnv is missed, I hope the firmware can rebuild a new one.

**Comment by jclehner** [comment]
> BTW: Partition permnv is missed, I hope the firmware can rebuild a new one.

Yes, it should be able to, apart from the serial number and mac addresses. You can set these using `bcm2cfg`.

**Comment by yq2018** [comment]
Thank you for your remind.

After the bootloader write to flash, TC7200 is running again.
Because little knowledge about eCos and DOCSIS3.0,  I meet problem to rebuild the permnv. 
It cannot create connection with Vodafone cable network. The LED of DS&US&Online blink. DS&US on while Online off, then Online on while DS&US off.

TC7200 status page as following:
```
CM Software Information
Standards Compliancy  DOCSIS 3.0 
Software Version:  STD6.02.41 
Hardware Version 2.0. 
HFC MAC Address 00:10:95:xx:xx:xx
Gateway Serial Number

Installed Certification
    EuroDOCSIS: Not installed
    DOCSIS: Not installed
    EuroPacketCable: Not installed 

System Uptime  0 days 00h:13m:28s 

Network Access Denied
CM IP Address  ---.---.---.--- 
```

The item "Network Access" is "Denied", maybe the root cause is certification not installed. The above group "Installed Certification" includes EuroDOCSIS, DOCSIS, EuroPacketCable, they should be installed both. I tried to use bcm2cfg and enter eCOS CM prompt, but I have no idea how to install these certification.   

Now I have another working EPC3008 now, the TC7200.U is expected to be repaired as backup and test environment. I will try more to recover it when have more free time.

Thank you again for all your help and great bcm2-utils tools.

**Comment by jclehner** [comment]
Yes, the modems own certificates will be lost, so there's no way to get it to register on the network again, aside from cloning the permnv contents from another device.
