### ISSUE TITLE
EPC3008 permnv settings are not added

### ISSUE THREAD

**Issue by mediotex** [jclehner/bcm2-utils#39]
I changed some permnv.bin settings (CM DOCSIS NonVol Settings), and used bcm2dump to write permnv back.
Then I rebooted modem and dumped permnv.bin, then I checked  section data that I have  modified in docsis1 and halif group, the settings have been saved OK. ("CM DOCSIS NonVol Settings")
But when I checked that permnv settings from CLI interface
` CM/Console/system> show nonvol `
the output show old, unchanged settings: so  in fact, it turns out that these settings were not applied.
Where are stored these permnv settings?

**Comment by jclehner** [comment]
Hi Alex,

I've just noticed that the `permnv` and `dynnv` files actually include a wear leveling mechanism, that I somehow missed the last 6 years ¯\_(ツ)_/¯.  I've pushed a new commit, but haven't had time to thoroughly test this yet!

**Comment by mediotex** [comment]
Hi Joseph,
I tried bcm2-utils with the latest commit added, but there is no change.

**Comment by jclehner** [comment]
I've pushed a new commit, that removes all remnants of old config data (39b90b8). Work in progress, as before. Does that fix your issue?

**Comment by mediotex** [comment]
Tested new commit #39b90b8 to write `permnv`: no difference.

```
./bcm2dump -FF -L write.log -vv write /dev/ttyUSB0 flash permnv permnv.bin
bcm2dump 
detected interface: bootloader
adjusting dump params: 0x807023d4,7 -> 0x807023d4,8
adjusting dump params: 0x80f89da0,11 -> 0x80f89da0,12
adjusting dump params: 0x82f00014,6 -> 0x82f00014,8
adjusting dump params: 0x83e05bb8,11 -> 0x83e05bb8,12
detected profile epc3008(bootloader), version 2.3.1_R3
updating code at 0xa0010000 (736 b)
 100.00% (0xa00102df)              10  bytes/s (ELT      00:01:07)
writing flash:0x00010000-0x0001ffff (65536 b)
 100.00% (0x0001ffff)             500  bytes/s (ELT      00:02:11)
./bcm2dump -L dump.log -vv dump /dev/ttyUSB0 flash permnv permnv_test.bin
bcm2dump 
detected interface: bootloader
adjusting dump params: 0x807023d4,7 -> 0x807023d4,8
adjusting dump params: 0x80f89da0,11 -> 0x80f89da0,12
adjusting dump params: 0x82f00014,6 -> 0x82f00014,8
adjusting dump params: 0x83e05bb8,11 -> 0x83e05bb8,12
detected profile epc3008(bootloader), version 2.3.1_R3
updating code at 0xa0010000 (428 b)
 100.00% (0xa00101ab)              11  bytes/s (ELT      00:00:38)
dumping flash:0x00010000-0x0001ffff (65536 b)
 100.00% (0x0001ffff)            4.57k bytes/s (ELT      00:00:14
```

[write.log](https://github.com/jclehner/bcm2-utils/files/7534554/write.log)
[dump.log](https://github.com/jclehner/bcm2-utils/files/7534555/dump.log)

**Comment by jclehner** [comment]
Please also send the corresponding bin files (via email).

**Comment by jclehner** [comment]
Perhaps I wasn't clear. The issue was in `bcm2cfg`, not `bcm2dump`. Please run your `bcm2cfg set` commands again, then try flashing the file.

**Comment by jclehner** [comment]
Today I had time to do some testing on actual hardware, and it looks like my previous statement about a wear-leveling mechanism was wrong. It actually appears as if the firmware always stores two copies of the data, one as a primary, and the other one as a backup. If the primary data is corrupted, it falls back to the backup data.

I've pushed some commits today, but there's still more testing to do, so please be patient.

**Comment by jclehner** [comment]
Please try the latest commits. After some reverse engineering and trial and error, I think I've finally figured it out. I've updated the documentation in [FORMAT.md](https://github.com/jclehner/bcm2-utils/blob/master/FORMAT.md#old-style-pre-bcm3390), in case you're interested.

**Comment by mediotex** [comment]
Yes, it works. I tested on original (unmodified) copies of permnv and dynnv.
When run bcm2cfg `info` on permnv/dynnv files, that have been modded by previous bcm2cfg patches , sometimes it show warning. Haven't tried to flash them though.

./bcm2cfg -f perm info permnv.bin
read invalid segment bitmask: 0xfffffff3  (0xfffffff2)
permnv.bin
type    : perm
profile : (unknown)
checksum: a9d68888 (ok)
size    : 9925 (ok)
...

./bcm2cfg -f dyn info dynnv.bin 
read invalid segment bitmask: 0xfffffffa
dynnv.bin
type    : dyn
profile : (unknown)
checksum: dfcddab4 (ok)
size    : 30307 (ok)
...

**Comment by jclehner** [comment]
Awesome! Closing this now!
